### ISSUE TITLE
Rebass inspiration

### ISSUE THREAD

**Issue by steida** [dabit3/React-Native-Elements#1]
Nice work! Have you seen https://github.com/jxnblk/rebass? I think it's the most clean approach.

**Comment by martinezguillaume** [comment]
Example app for the last commit (2be1ae99b19ab2a9639a8fb42ab3d5a843f21573):

![QR Code](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://exp.host/@rn-elements/react-native-elements-app?release-channel=2be1ae99b19ab2a9639a8fb42ab3d5a843f21573)

https://exp.host/@rn-elements/react-native-elements-app?release-channel=2be1ae99b19ab2a9639a8fb42ab3d5a843f21573
