### ISSUE TITLE
[Error]The development server returned response error code:500

### ISSUE THREAD

**Issue by JeffersonFilho** [dabit3/React-Native-Elements#4]
Hello,

Thanks for build this awesome toolkit! Unfortunately when I try `import { Button } from 'react-native-elements'` or anything I get this error:

![error-500](https://cloud.githubusercontent.com/assets/4169422/18414000/495977ba-77b2-11e6-9258-6a5c67b953f1.jpg)
 
Any idea why?

Thanks!

**Comment by JeffersonFilho** [comment]
I fixed this error by going inside of the react-native-elements folder and running `npm install`

**Comment by manukumarmnk** [comment]
Hi @JeffersonFilho, I tried your step but still i'm getting same error.

**Comment by Dmitry052** [comment]
Run the following commands:
- npm i react-native-vector-icons --save && react-native link react-native-vector-icons
- npm i react-native-elements --save

**Comment by sohelkhanid** [comment]
Hi @JeffersonFilho, I tried your step but still i'm getting same error.
my dependencies are
"dependencies": {
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-elements": "^0.19.1",
    "react-native-image-slider": "^2.0.3",
    "react-navigation": "^2.11.2"
  }

**Comment by JeffersonFilho** [comment]
Has been few years since I used this package, but I will try to setup it tonight again and see if I run into this error again to see if I can guide you guys to fix it too.

**Comment by Jcdroid** [comment]
@sohelkhanid you can use `npm add @babel/runtime` or `yarn add @babel/runtime`, detail see [here](https://github.com/jquense/yup/issues/216).
