### ISSUE TITLE
Lato on iOS

### ISSUE THREAD

**Issue by brentvatne** [dabit3/React-Native-Elements#5]
Why default to Lato on iOS? People who install this library will have to then install that font and increase the size of their app :( San Francisco is a pretty good default font. 

In particular this is problematic with Exponent where we don't ship with that font and have a separate way of loading fonts into the app that would be incompatible with this.

**Comment by dabit3** [comment]
When I created this, I was really building a boilerplate, which was using Lato as the font. I then pulled the elements out and moved them into this project when I created it. I too def think it's better to default to a system font and I have been considering what to do, glad to get this feedback.

Question, I also have[ react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) as a dependency. Will Exponent work with react-native-vector-icons when I replace Lato with a system font?

**Comment by dabit3** [comment]
I just noticed that exponent has it's own vector icons library. Any pointers as to what I need to change in the api to work with the exponent icon set? Do I need to check to see if the app is running exponent and then `import { } from '@exponent/vector-icons'` if so?

**Comment by brentvatne** [comment]
@dabit3 - already made this work and submitted a PR :)

**Comment by dabit3** [comment]
Wow thanks, this looks great. I'll be looking more into Exponent so I can understand how it works to make future features compatible. Also may do a blog post about rapid prototyping with this library + Exponent for a talk I'm giving next week about R N for Web Developers at Northeast JS Conference, so I'm glad it now will already work with Exponent.

One final question, can you explain some of the changes in package.json if you have a moment. I'm still trying to wrap my head around what is and isn't necessary there for a project like this.

Again, thanks for this pr.

**Comment by dabit3** [comment]
Hey, never mind about the explanations about package.json, I see you left some feedback in the pull request!
